### PR TITLE
Update addon.py

### PR DESCRIPTION
**Pull request by mikimac**
Fix for regx to with all categories, and other listitems since old one was opening only Top Rated.

### CODE REVIEW

**Comment by mrdougquaid** [comment]
Please revert the white space changes, in general do not change the style if the code you are modifying.
Make the minimal number of changes in each commit

**Comment by mikimac** [comment]
Sorry for white space changes. I have fixed that and updated file.

**Comment by mrdougquaid** [comment]
Please merge these commits into one single commit. We don't need to see all the different steps which lead to the final result

**Comment by mrdougquaid** [comment]
I have fixed the regex myself.
Thanks for the pull request but I was not able to use it this time. It is really important to make minimal diffs, this pull was hard to read.

**Pull request closed without merging**
