### PR TITLE
Fix Youporn, Spankwire, Motherless

### PR DESCRIPTION
**Pull request by Vashiel**
Okey, let's start from the beginning. Rebasing. Fixes will be seperate from new features.
- Youporn, Spankwire wrong or missing cookie line
- Motherless Video will not jump forward, unless you remove that line. Maybe it was needed  back in the days when Motherless used flash, but now it just stops Videoplayback when you jump forward.

### CODE REVIEW

**Comment by mrdougquaid** [comment]
Revert spankwire and youporn so that I can merge the request otherwise I will just cherry-pick motherless

**Comment by Vashiel** [comment]
Hi mrdougquaid, Tried (again 5mins ago) with Xbmc 13.2 on an Android MX Box, Windows PC and a Linux HTPC. Without that  Cookie line Youporn shows just a empty folder and Spankwire gives Error "Error runing VideoDevil. Reason (22,'Invalid argument'). With that line it just works fine on Android, Windows and Linux. Also checked my Chrome addon "EditThisCookie" and i can see this cookie "adultd=1". Why does it work for you without that line? What kind of XBMC or Box are you using?

**Comment by mrdougquaid** [comment]
I will try with a clean profile to see if I can reproduce

**Comment by Vashiel** [comment]
Hi mrdougquaid, I found out why you don't need a cookie to enter those sites and i need that cookie. It has do to with your Country. If you have, for example, a IP from U.S.A, you can enter the sites without a problem. BUT if you enter the page from Germany (like me) , youporn directs you the a page with a warning that you have to be 18 to enter the site. You have to click enter and a cookie age_verified=1 is set. So Germany can't enter without  that cookie (other Countries may have the same problem, don't know). Spankwire, same problem, diffent cookie. For U.S.A (also for U.K, China, Switzerland) that cookie makes no difference. You may reproduce the problem by using a german proxy (Chrome, Zenmate and EditThisCookie should do the trick).

**Pull request merged**
