### PR TITLE
Fix xHamster support in VideoDevil

### PR DESCRIPTION
**Pull request by Firegolem69**
Fix parsing of category and video URLs on empflix.com.

### CODE REVIEW

**Comment by mrdougquaid** [comment]
Please fix commit message this is fixing xhamster in videodevil

**Comment by Firegolem69** [comment]
I'm sorry, it was too late. Fixing...

**Comment by Firegolem69** [comment]
What are your thoughts? Do you need me to make any more changes to this PR?

**Comment by mrdougquaid** [comment]
This doesn't seem to fix xhamster

**Comment by mrdougquaid** [comment]
Closing as it has been fixed by another commit

**Pull request closed without merging**
