### PR TITLE
Videodevil Fixes

### PR DESCRIPTION
**Pull request by Gujal00**
Multiple site fixes.
Please hold off releasing as I want to add a few more fixes

### CODE REVIEW

**Comment by Gujal00** [comment]
All done. Please verify and merge at your convenience

**Review by mrdougquaid — COMMENTED** [review]
Couldn't reproduce this. I get the messages without changing the log level to LOGNOTICE just by changing the setting in the addon

**Comment by Gujal00** [comment]
This hasn't worked for me since Kodi 16.x release. I will recheck again on a clean Kodi 17.6 install and let you know. Thanks

**Comment by Gujal00** [comment]
With Kodi >16 there are no debug messages in the log when VIdeodevil debug is enabled unless Kodi itself is put into debug mode, which makes the log unreadable as there is so much kodi debug spew along with the videodevil debug messages,
With my change above to include LOGNOTICE, when videodevil debug is enabled, and Kodi is not set to debug, the log contains the debug messages from videodevil only and is easily readable and useable

**Comment by mrdougquaid** [comment]
OK thanks for looking
Added

**Pull request closed without merging**
