### PR TITLE
[VideoDevil] fix GirlfriendVideos and XHamster gay categories

### LINKED ISSUE #409: GirlfriendVideos stopped working
Every section of the menu is empty. Started a couple of weeks ago.

(Thanks for the plugin, BTW)

### PR DESCRIPTION
**Pull request by ghost**
- Fixed GirlfriendVideos video link regex
- Fixed situation when `title` already containing `title.append` was overwritten by original value because of dictionary key order. This resulted in duration missing in the title of several website listings.
- Fixed XHamster gay category listing

### CODE REVIEW

**Comment by mrdougquaid** [comment]
Could you split  0973565 into 3 commits ? One for each file? 

Thanks for the fixes

**Comment by ghost** [comment]
> Could you split [0973565](https://github.com/xbmc-adult/xbmc-adult/commit/097356565279f811fecce294a56c22c4f8e5532f) into 3 commits ? One for each file?
> 
> Thanks for the fixes

Will do.

**Comment by ghost** [comment]
@mrdougquaid Done

**Comment by mrdougquaid** [comment]
Merged thanks!

**Pull request closed without merging**
