### PR TITLE
fixed faapy + added "no video found" notifcation

### PR DESCRIPTION
**Pull request by snokkers**

### CODE REVIEW

**Comment by mrdougquaid** [comment]
I will need some time to review this.
The dialog box for the notification does the user have to click on anything to dismiss it? I would rather not if it does.
If you split the two commits into two separate pulls I can merge the faapy one

**Comment by mrdougquaid** [comment]
I cherry picked the faapy fix thanks
I will need more time for the error notification. Does the popup need to be dismissed? I'd rather not have the user have to dismiss the dialog, it's just annoying

**Comment by snokkers** [comment]
It does not need to be dismissed. it also does not block the ui in any way. its just an overlay notification popup disappearing quite quick.

**Comment by mrdougquaid** [comment]
It beeps when it appears. I am not a fan of this so I removed the beep.

Thanks!

**Pull request merged**
